import { Header } from './components/header/page';
import './globals.css';

export const metadata = {
  title: 'Star Wars Api Demo',
  description: 'Made by Mihály Pápay, Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        <link rel="icon" href="/death-star-bold.svg" />
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
